language: python
python:
- '3.5'
install: pip install -r requirements.txt
before_script:
- psql -c 'create database test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: db80f594-665a-4ad8-b3fa-96bf6d2db9ba
  app: fiberappz
  on:
    repo: fabiocostapro/fiberappz
script: pytest
