language: python
python:
- '3.5'
install: pip install -r requirements.txt
before_script:
- psql -c 'create database test;' -U postgres
script: pytest
deploy:
  provider: heroku
  api_key:
    secure: VdsGy8jRjBYHogzkTb7YgxQe4Zspv0w9p4xqpBhF+DJxp3ClKFrNkW/dDfK6Lr9BtrRM+IEMOvqxjpZykGaiGKSHWEkB+dw1xdQlq6FUlxVwdEUX5K+oMGCk7s1qYSH+A5wQz0eI0RIN2e3w61/XivXRrjoStgIltaBDzmpoYzzLP/hH41r2CwM6PUYoEJhzsC1hHXVfZP0jkfRbiBoHChGPzOAHwxz6rqSFBmDXriKVNgpmprl3gPMVBRav3t+/CQ1qXsIfTy2qVjo5LyEJkW2j7Gj/9Y0UVCDNp2Ywp+2ot1bTpVUyoKo/+RQDrYtch0QVZzKZr5t+0qtWUAZDrl+v3agfXHBRkF1imd0JKulSoxyUQ429kM919jxDuGsUC0hpODyiKN6UlKVTlQxLMtMfDO2xGY3ih0abWTGBC+ZLIC3zWH7+hhHo+wb7a0ysZUHjZLfCMFaMH4SSsb4ce5mjeEUIN8zFfNEW0x1V4pNxSgrYsljcgi/AK7ekYNbNdefWZjmBlTDSC8LeK5gbfkwGOOCb2DkX0pLcNtY5hQEISQ/OcBwPY/HnvggNpz/Ove3/jaXpX8NXYxJnwppFKwZVxODZYmNBWrCe1YFffvAqPrUYrm6mm8BI2rMCydwVl3A4FQgxa9QlX486wkm6jr3niS0XcZ6Uf3MdoQkgD+A=
  app: fiberappz
  on:
    repo: fabiocostapro/fiberappz
