language: python
python:
- '3.5'
install: pip install -r requirements.txt
before_script:
- psql -c 'create database test;' -U postgres
deploy:
  provider: heroku
  app: fiberappz
  on:
    repo: fabiocostapro/fiberappz
  api_key:
    secure: lRvKwibp5lidx5zzALHr/i81Zl438NacpBrNv2g1/yoHlqwb+Ps+b8U2CEUHOu9vi13RYzDPguyuqZe8DqWYZmnWSPkLSrRc2Ct03bunjQysUvcI9ml5IsYZ/Wk1iIE+MreJvSfn/hksdrayKq9TPUEf0hpQYHsqinaHHQ8/ebtjDWUsRwnY4BobY4bwXEjQ8sJhyk339HOgoennWR3t4ZgB61ReACsViTZ4xshNdSMD6rZpTkoOmrgFVJrRTunpmkQZ82nQy7PKghHB4tvS5xNjALAhSordW2V3DlOHm5AC3yE9SqEqz+3NLYNqPp3pw5jeg7MSeaXRhvMQG+RvGCbPJKTJUaBkUO5pRdxW3Wdf7j+1KRwctaH1l5nuAHAxNBz+G/BmrgbxmtELroqg5alO+MvQetp9qrk6DW7K2n2QFAhSPo3LOlxf5XQ/8uUvA+UcF/MIT7F1itkxvXbh0oAeWObDEyDYLcanB+o1Oog9lHrvv/mkvwVx0EwSD9ghr4N6m+V68GgbfAqXObDXnFUiMJc8uKVhGxEr6mQAi7dqEppkL8zT21pCY4cwvuu84eIRGPrBHaZ18IiwMdhAien3lWTZcf99qZSJ5FYuN/I4Ft3Pd0tPG8bWtKsxCy87xO0i2VqiOjTTirEHs7z7zwpD/1Bat/RzfeLDcb2uY9E=
script: pytest
env:
  global:
    secure: Ncplls2GCcQzeRUMv0Qk7kvcDEXKA45cE13YIoJgkmmTnisI/LGQHnh2eX14VEjEFz/Uk6TzRXd4W7bzkW3YWY4hGG1fjhuj52iuKmeg53UUdKDcVDJXI7FoBVTJH3hnoFDnhY3WpKwX4wO6+qGqGz815quL1/zkpSM6WmU7wLq09FsRSR/C7+Fi++dlYS3NDROqA/Im3XnDVNTfuVrnbzWc6KB6BR5oRMMnyzxlVT/+xVNfZJqDOT6Sip5XEYeSUx2wg1RV22bqEIncxZsD9TvT3WvmgGfLunW9+jF58k+kQRJVNzFrzFplxnDUsrqVK0kAAHPjOVeLyfpFTkrj7XRN4aS+dcRyml9pFmHAfhHvOAbgNXKJx4zUe4WcXa5gTTPvIPikfi7fLIzdEXJIFmiVLqP4aFIsX2p8+FNmfdpXzm/jRfHIQv5wyqEkmk6dIPecx1qfhgScn+wbCkrnezJkVtgN8zVGMYerM5foE3TN2zFAg5dj6IcsCMTLUXf2caRaG1UgHGemwG3sNorT9v17IzRkurinYbUn5SPjM1EQsBNT170WMrWG3tojz9mRmTRnmGlpJcLR3RKOgic7brj0+WUEqD1H4Q5c6Wg7ISMB9xIoJ7i9bTPF+tjh3LVT4mwfXQ9nIl0uaUoIbC3rl48AYVvnQKO4F47X2EID40Q=
